#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'DisplayPort-1 connected') ]]; then
xrandr --output eDP --primary --mode 1920x1080 --pos 0x660 --rotate normal --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --mode 3840x2160 --pos 1966x0 --rotate normal
fi

bspc monitor eDP1 -d 6 7 8 9 10
bspc monitor DisplayPort-1 -d 1 2 3 4 5

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
