#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'DisplayPort-1 connected') ]]; then
# xrandr --output eDP --mode 1920x1080 --pos 0x660 --rotate normal --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --primary --mode 3840x2160 --pos 1985x0 --rotate normal
xrandr --output eDP --off --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --primary --mode 3840x2160 --pos 0x0 --rotate normal
bspc monitor DisplayPort-1 -d I II III IV V VI VII VIII IX X
else
    bspc monitor eDP -d I II III IV V VI VII VIII IX X
fi

$HOME/.config/polybar/launch.sh


bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-center ~/Downloads/wallpaper.png 

setxkbmap -option ctrl:nocaps
